In [2]:
import numpy as np

## Problem 4

### 4c.

Generating 3 3x3 matrices

In [14]:
a = np.random.randint(-10, 11, (3, 3))
b = np.random.randint(-10, 11, (3, 3))
c = np.random.randint(-10, 11, (3, 3))
print('a:')
print(a)
print('b:')
print(b)
print('c:')
print(c)

a:
[[-8 -9  8]
 [-8  3 -3]
 [ 9  5 -3]]
b:
[[ 9  6 -2]
 [-3 -8 -7]
 [ 8 10  5]]
c:
[[-9 -2 -9]
 [-6  4  8]
 [-1  7 -1]]


Computing Inverses

In [15]:
a_inv = np.linalg.inv(a)
b_inv = np.linalg.inv(b)
c_inv = np.linalg.inv(c)

print('a^-1:')
print(a_inv)
print('b^-1:')
print(b_inv)
print('c^-1:')
print(c_inv)

a^-1:
[[-0.048 -0.104 -0.024]
 [ 0.408  0.384  0.704]
 [ 0.536  0.328  0.768]]
b^-1:
[[-0.68181818  1.13636364  1.31818182]
 [ 0.93181818 -1.38636364 -1.56818182]
 [-0.77272727  0.95454545  1.22727273]]
c^-1:
[[-0.06593407 -0.07142857  0.02197802]
 [-0.01538462  0.          0.13846154]
 [-0.04175824  0.07142857 -0.05274725]]


Computing product of each matrix with it's inverse

In [17]:
print('aa^-1:')
print(np.matmul(a, a_inv))
print('bb^-1:')
print(np.matmul(b, b_inv))
print('cc^-1:')
print(np.matmul(c, c_inv))

aa^-1:
[[ 1.00000000e+00 -4.44089210e-16  0.00000000e+00]
 [-3.33066907e-16  1.00000000e+00 -2.22044605e-16]
 [ 1.11022302e-16 -5.55111512e-17  1.00000000e+00]]
bb^-1:
[[ 1.00000000e+00 -8.88178420e-16 -8.88178420e-16]
 [ 0.00000000e+00  1.00000000e+00  1.77635684e-15]
 [-8.88178420e-16  4.44089210e-16  1.00000000e+00]]
cc^-1:
[[ 1.00000000e+00 -1.38777878e-16  2.08166817e-17]
 [ 1.66533454e-16  1.00000000e+00  5.55111512e-17]
 [ 0.00000000e+00 -1.38777878e-17  1.00000000e+00]]


## Problem 5

### 5a.

Averages of each feature

In [68]:
import pandas as pd

df = pd.read_csv('kc_house_data.csv')
df_features = df.drop(['id', 'date', 'zipcode', 'price'], axis=1)
np.mean(df_features)

bedrooms             3.370842
bathrooms            2.114757
sqft_living       2079.899736
sqft_lot         15106.967566
floors               1.494309
waterfront           0.007542
view                 0.234303
condition            3.409430
grade                7.656873
sqft_above        1788.390691
sqft_basement      291.509045
yr_built          1971.005136
yr_renovated        84.402258
lat                 47.560053
long              -122.213896
sqft_living15     1986.552492
sqft_lot15       12768.455652
dtype: float64

Variance of each feature

In [69]:
np.var(df_features)

bedrooms         8.649750e-01
bathrooms        5.931238e-01
sqft_living      8.434947e+05
sqft_lot         1.715579e+09
floors           2.915745e-01
waterfront       7.484879e-03
view             5.872154e-01
condition        4.234469e-01
grade            1.381639e+00
sqft_above       6.857029e+05
sqft_basement    1.958636e+05
yr_built         8.627573e+02
yr_renovated     1.613387e+05
lat              1.919901e-02
long             1.983170e-02
sqft_living15    4.697395e+05
sqft_lot15       7.454837e+08
dtype: float64

Minimum of each feature

In [70]:
np.min(df_features)

bedrooms            0.0000
bathrooms           0.0000
sqft_living       290.0000
sqft_lot          520.0000
floors              1.0000
waterfront          0.0000
view                0.0000
condition           1.0000
grade               1.0000
sqft_above        290.0000
sqft_basement       0.0000
yr_built         1900.0000
yr_renovated        0.0000
lat                47.1559
long             -122.5190
sqft_living15     399.0000
sqft_lot15        651.0000
dtype: float64

Maximum of each feature

In [93]:
np.max(df_features)

bedrooms         3.300000e+01
bathrooms        8.000000e+00
sqft_living      1.354000e+04
sqft_lot         1.651359e+06
floors           3.500000e+00
waterfront       1.000000e+00
view             4.000000e+00
condition        5.000000e+00
grade            1.300000e+01
sqft_above       9.410000e+03
sqft_basement    4.820000e+03
yr_built         2.015000e+03
yr_renovated     2.015000e+03
lat              4.777760e+01
long            -1.213150e+02
sqft_living15    6.210000e+03
sqft_lot15       8.712000e+05
dtype: float64

## 5b.

Table of correlation coefficient of each feature with price

In [90]:
df.corr(method='pearson')['price'].drop(['id', 'zipcode', 'price'])

bedrooms         0.308350
bathrooms        0.525138
sqft_living      0.702035
sqft_lot         0.089661
floors           0.256794
waterfront       0.266369
view             0.397293
condition        0.036362
grade            0.667434
sqft_above       0.605567
sqft_basement    0.323816
yr_built         0.054012
yr_renovated     0.126434
lat              0.307003
long             0.021626
sqft_living15    0.585379
sqft_lot15       0.082447
Name: price, dtype: float64